# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: FreedomScientific.JAWS.2024
PackageVersion: 2024.2409.2.400
InstallerType: burn
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
Installers:
- Architecture: x64
  InstallerUrl: https://software.vfo.digital/JAWS/2024/2024.2409.2.400/3E33D4C2-B65B-4A4A-BC62-4C1A540CB3DB/J2024.2409.2.400-any.exe
  InstallerSha256: 6FB64991B4404658D20BA0E3D84A1862E834C63981768DA62E5E6C3223024344
ManifestType: installer
ManifestVersion: 1.6.0
